### ISSUE TITLE
Make more robust the Travis CI notifications on failures in master

### ISSUE THREAD

**Issue by lucafavatellawork** [opensparkl/sse_cli#94]
A [recent cron CI build failure in master](https://github.com/opensparkl/sse_cli/issues/93) was not notified to any member/contributor of the repo. CI notifications shall be made more robust.

**Comment by lucafavatellawork** [comment]
The simplest solutions seems to be [configuring email notifications](https://docs.travis-ci.com/user/notifications/#configuring-email-notifications) - either with direct email addresses or mailing list. That reference has the following example:
```yaml
notifications:
  email:
    - one@example.com
    - other@example.com
```
